### ISSUE TITLE
KW Changes

### ISSUE THREAD

**Issue by DJTB** [username-Halo/userscripts#1]
Just a heads up to hold off on any TODOs you have, because *everything* will break horribly with the next update (new markup, generated class names etc).

It'd be better to join slack (after the next release) to discuss incorporating some of your features natively ^^

**Comment by username-Halo** [comment]
Oh. The long awaited Next Update. Nice. 
Though I was too lazy to even fix some minor mistakes, let alone to implement new features. But now I have a legitimate reason to continue do nothing. Thanks.
