### ISSUE TITLE
WaniKaniVG

### ISSUE THREAD

**Issue by DJTB** [username-Halo/userscripts#2]
You can have fun with animations too if you take a look at [dmak](https://github.com/mbilbille/dmak) which is set up to use the KanjiVG data.

**Comment by username-Halo** [comment]
I had it implemented via [vivus](https://github.com/maxwellito/vivus). It's nice to look at, but it was way too distracting as a study reference.

**Comment by DJTB** [comment]
Oh that's a nice looking library; I wasn't aware of it... hmm.
I'm still undecided if the separate stroke step images are more convenient than an animation.
I might just offer either and leave it to user preference.

Do you still have an example with vivus hanging about?

**Comment by username-Halo** [comment]
No, but [there's](https://codepen.io/username-Halo/pen/RgXyOY) a very quick example. Though it looks nicer with a better customization and some transactions. 

> leave it to user preference.
First I need to make the preferences ¯\_(ツ)_/¯

**Comment by DJTB** [comment]
FYI: Too lazy to make a PR -> `waniKaniVG.user.js 49:7` should be `</style>` ^^

**Comment by username-Halo** [comment]
Thanks.
